# This is a basic workflow to help you get started with Actions

name: Unit tests SBCL

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        lisp:
          - sbcl-bin
          # - clisp # Fails to install
          # - ccl-bin # Takes too long to run (more than 10 minutes)
          # - clasp-bin # LLVM library is missing from ubuntu-latest?
          # - cmu-bin # Fails to install
          # - ecl # Fails to install
          # - abcl-bin # Fails to install
          
    env:
      LISP: ${{ matrix.lisp }}
      
    steps:
      - uses: actions/checkout@v1
      - uses: 40ants/setup-lisp@v1
        with:
          asdf-system: jshell4cl
      - name: Run tests manually, the automatic fails with installation of cl-coveralls
        run: ros run -s cl-morse -e "(asdf:test-system :jshell4cl)" -q
      #- uses: 40ants/run-tests@v2 # TODO why this fails??
      #  with:
      #    asdf-system: cl-morse
#       - name: Run critic
#         run: |
#           ros install  40ants/40ants-critic
#           lisp-critic cl-morse
        
